core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import Dashboard, Wallet, SendCrypto, CreateUser, logout_user, ReceiveCrypto


app_name = 'core'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('wallet/', Wallet.as_view(), name='wallet'),
    path('send/', SendCrypto.as_view(), name='crypto_send'),
    path('receive/', ReceiveCrypto.as_view(), name='crypto_receive'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', CreateUser.as_view(), name='register'),
]

stoke/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4



class UserWallet(models.Model):
    COIN = [
        ('btc', 'btc'),
        ('ltc', 'ltc'),
        ('eth', 'eth'),
    ]

    id = models.UUIDField(default=uuid4, editable=False, primary_key=True, unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    balance = models.FloatField()
    address = models.CharField(max_length=50)
    currency = models.CharField(max_length=200, choices=COIN, default=COIN[0][0])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user.username} | {self.currency.upper()} | {self.address}'

    def get_total_balance(self) -> int:
        total = 0
        user_transactions = self.objects.filter(user=self.user)
        for i in user_transactions:
            total + i.balance
        return total


class TransactionHistory(models.Model):
    COIN = [
        ('btc', 'btc'),
        ('ltc', 'ltc'),
        ('eth', 'eth'),
    ]

    TRANSACTION_TYPE = [
        ('out', 'out'),
        ('in', 'in'),
    ]
    id = models.UUIDField(default=uuid4, editable=False, primary_key=True, unique=True)
    transaction_ref = models.CharField(max_length=50, unique=True)
    # wallet = models.ForeignKey(to=UserWallet, on_delete=models.CASCADE)
    amount = models.IntegerField()
    transaction_type = models.CharField(max_length=3)
    currency = models.CharField(max_length=200, choices=COIN, default=COIN[0][0])
    from_address =  models.CharField(max_length=100)
    to_address =  models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Currency: {self.currency} | Ref: {self.transaction_ref} | Sent From: {self.from_address} | Sent To: {self.to_address}'
    
    def get_total_received(self) -> int:
        total = 0
        user_transactions = self.objects.filter(transaction_type='in')
        for i in user_transactions:
            total + i.amount
        return total

    def get_total_sent(self):
        pass

core/forms.py
from django import forms
from .models import TransactionHistory



class SendCryptoModelForm(forms.ModelForm):
    class Meta:
        model = TransactionHistory
        exclude = ['transaction_ref', 'transaction_type', 'from_address', 'to_address']

core/views.py
from typing import Any
from uuid import uuid4
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.db.models.query import Q

from .models import TransactionHistory, UserWallet
from .forms import SendCryptoModelForm





def get_random_text(legnth: int) -> str:
    return uuid4().hex[:legnth]


class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'core/dashboard.html'

    def get_queryset(self) -> QuerySet[Any]:
        return TransactionHistory.objects.filter(pk=self.request.user.pk)


class Wallet(LoginRequiredMixin, ListView):
    template_name = 'core/wallet.html'
    
    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        user_wallets = self.get_queryset()
        eth_wallet_address = user_wallets.get(currency='eth').address
        btc_wallet_address = user_wallets.get(currency='btc').address
        ltc_wallet_address = user_wallets.get(currency='ltc').address

        all_sent_transaction = TransactionHistory.objects.filter(
            Q(from_address=eth_wallet_address) | 
            Q(from_address=btc_wallet_address) | 
            Q(from_address=ltc_wallet_address) 
        ).order_by('-created_at')

        all_received_transaction = TransactionHistory.objects.filter(
            Q(to_address=eth_wallet_address) | 
            Q(to_address=btc_wallet_address) | 
            Q(to_address=ltc_wallet_address) 
        ).order_by('-created_at')

        # Get Total User Wallet Balance
        total_balance = 0.0
        for wallet in user_wallets: total_balance += wallet.balance

        total_sent_amount = 0.0
        for transaction in all_sent_transaction: total_sent_amount += transaction.amount

        total_received_amount = 0.0
        for transaction in all_received_transaction: total_received_amount += transaction.amount

        
        # Contexts]------------------------------------------
        # Sent Transactions
        context['all_sent_transactions'] = all_sent_transaction
        context['sent_eth_transactions'] = TransactionHistory.objects.filter(from_address=eth_wallet_address).order_by('-created_at')
        context['sent_btc_transactions'] = TransactionHistory.objects.filter(from_address=btc_wallet_address).order_by('-created_at')
        context['sent_ltc_transactions'] = TransactionHistory.objects.filter(from_address=ltc_wallet_address).order_by('-created_at')

        # Received Transactions
        context['all_received_transaction'] = all_received_transaction
        context['received_eth_transactions'] = TransactionHistory.objects.filter(to_address=eth_wallet_address).order_by('-created_at')
        context['received_btc_transactions'] = TransactionHistory.objects.filter(to_address=btc_wallet_address).order_by('-created_at')
        context['received_ltc_transactions'] = TransactionHistory.objects.filter(to_address=ltc_wallet_address).order_by('-created_at')
        
        # Totals
        context['total_balance'] = total_balance
        context['total_sent_amount'] = total_sent_amount
        context['total_received_amount'] = total_received_amount
        return context


class SendCrypto(LoginRequiredMixin, CreateView):
    template_name = 'core/crypto_send.html'
    form_class = SendCryptoModelForm

    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)

    def get_success_url(self) -> str:
        return resolve_url('core:wallet')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        try:
            send_amount = int(form.cleaned_data.get('amount'))
            currency = form.data.get('currency')
            address = form.data.get('address')
            wallet = UserWallet.objects.get(user=self.request.user.pk, currency=currency)
            recipient_wallet = UserWallet.objects.get(address=address)

            # check if send_amount is less than user wallet balance
            if send_amount > wallet.balance:
                return render(
                        self.request, 
                        'core/crypto_send.html', 
                        {
                            'form': form, 
                            'error': f'Insufficient {currency.upper()} balance', 
                            'wallets': UserWallet.objects.filter(user=self.request.user.pk)
                        }
                    )
        
            # deduct send_amount from user wallet balance
            wallet.balance -= send_amount
            wallet.save()

            # add send_amount from user to recipient's balance
            recipient_wallet.balance += send_amount
            recipient_wallet.save()

            form.instance.transaction_ref = get_random_text(20)
            form.instance.transaction_type = 'out'
            form.instance.from_address = wallet.address
            form.instance.to_address = address
            form.instance.currency = currency
            
            return super().form_valid(form)
        
        except UserWallet.DoesNotExist:
            return render(
                        self.request, 
                        'core/crypto_send.html', 
                        {
                            'form': form, 
                            'error': f'Invalid wallet address', 
                            'wallets': UserWallet.objects.filter(user=self.request.user.pk)
                        }
                    )

    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['wallets'] = UserWallet.objects.filter(user=self.request.user.pk)
        return context


class ReceiveCrypto(LoginRequiredMixin, ListView):
    template_name = 'core/crypto_receive.html'

    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)


class CreateUser(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'core/register.html'
    success_url = '/login'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        # Create 3 User Wallets
        user = form.save()
        # ETH Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='eth',
        )
        # BTC Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='btc',
        )
        # LTH Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='ltc',
        )
        return super().form_valid(form)

def logout_user(request):
    logout(request)
    return redirect('core:login')

templates/core/inc/header.html
{% load static %}
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="{% url 'core:dashboard' %}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo.svg' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png' %}" alt="" height="17">
                    </span>
                </a>

                <a href="{% url 'core:dashboard' %}" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-light.svg' %}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png' %}" alt="" height="19">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect" id="vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="bx bx-search-alt"></span>
                </div>
            </form>

        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ms-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..."
                                    aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i
                                            class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" data-bs-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <img id="header-lang-img" src="{% static 'images/flags/us.jpg' %}" alt="Header Language" height="16">
                </button>
                <div class="dropdown-menu dropdown-menu-end">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item language" data-lang="en">
                        <img src="{% static 'images/flags/us.jpg' %}" alt="user-image" class="me-1" height="12"> <span
                            class="align-middle">English</span>
                    </a>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ms-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                    <i class="bx bx-fullscreen"></i>
                </button>
            </div>

            <!-- Notification -->
            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect"
                    id="page-header-notifications-dropdown" data-bs-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <i class="bx bx-bell bx-tada"></i>
                    <span class="badge bg-danger rounded-pill">3</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-end p-0"
                    aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0" key="t-notifications"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <a href="#!" class="small" key="t-view-all"> View All</a>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-primary rounded-circle font-size-16">
                                        <i class="bx bx-cart"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-your-order">Your order is placed</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the
                                            grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-min-ago">3
                                                min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="assets/images/users/avatar-3.jpg" class="me-3 rounded-circle avatar-xs"
                                    alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">James Lemire</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-simplified">It will seem like simplified English.
                                        </p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-hours-ago">1
                                                hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <div class="avatar-xs me-3">
                                    <span class="avatar-title bg-success rounded-circle font-size-16">
                                        <i class="bx bx-badge-check"></i>
                                    </span>
                                </div>
                                <div class="flex-grow-1">
                                    <h6 class="mb-1" key="t-shipped">Your item is shipped</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-grammer">If several languages coalesce the
                                            grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-min-ago">3
                                                min ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>

                        <a href="javascript: void(0);" class="text-reset notification-item">
                            <div class="d-flex">
                                <img src="assets/images/users/avatar-4.jpg" class="me-3 rounded-circle avatar-xs"
                                    alt="user-pic">
                                <div class="flex-grow-1">
                                    <h6 class="mb-1">Salena Layfield</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1" key="t-occidental">As a skeptical Cambridge friend of
                                            mine occidental.</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> <span key="t-hours-ago">1
                                                hours ago</span></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="p-2 border-top d-grid">
                        <a class="btn btn-sm btn-link font-size-14 text-center" href="javascript:void(0)">
                            <i class="mdi mdi-arrow-right-circle me-1"></i> <span key="t-view-more">View
                                More..</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="https://api.dicebear.com/7.x/thumbs/svg?seed={{user.username}}"
                        alt="Header Avatar">
                    <!-- <img class="rounded-circle header-profile-user" src="{% static 'images/users/avatar-1.jpg' %}"
                        alt="Header Avatar"> -->
                    <span class="d-none d-xl-inline-block ms-1" key="t-henry">{{ user.username }}</span>
                    <i class="mdi mdi-chevron-down d-none d-xl-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <!-- item-->
                    <a class="dropdown-item" href="#"><i class="bx bx-user font-size-16 align-middle me-1"></i>
                        <span key="t-profile">Profile</span></a>
                    <a class="dropdown-item" href="#"><i class="bx bx-wallet font-size-16 align-middle me-1"></i> <span
                            key="t-my-wallet">My
                            Wallet</span></a>
                    <a class="dropdown-item d-block" href="#"><span class="badge bg-success float-end">11</span><i
                            class="bx bx-wrench font-size-16 align-middle me-1"></i> <span
                            key="t-settings">Settings</span></a>
                    <a class="dropdown-item" href="#"><i class="bx bx-lock-open font-size-16 align-middle me-1"></i>
                        <span key="t-lock-screen">Lock screen</span></a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{% url 'core:logout' %}"><i
                            class="bx bx-power-off font-size-16 align-middle me-1 text-danger"></i> <span
                            key="t-logout">Logout</span></a>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon right-bar-toggle waves-effect">
                    <i class="bx bx-cog bx-spin"></i>
                </button>
            </div>

        </div>
    </div>
</header>

templates/core/inc/sidebar.html
{% load static %}
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title" key="t-menu">Menu</li>

                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="bx bx-home-circle"></i>
                        <span key="t-dashboards">Dashboards</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{% url 'core:dashboard' %}" key="t-default">Home</a></li>
                        <li><a href="{% url 'core:wallet' %}" key="t-saas">Wallet</a></li>
                        <li><a href="{% url 'core:logout' %}" key="t-saas">Logout</a></li>
                    </ul>
                </li>

            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->