core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import Dashboard, Wallet, SendCrypto, CreateUser, logout_user, ReceiveCrypto


app_name = 'core'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('wallet/', Wallet.as_view(), name='wallet'),
    path('send/', SendCrypto.as_view(), name='crypto_send'),
    path('receive/', ReceiveCrypto.as_view(), name='crypto_receive'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', CreateUser.as_view(), name='register'),
]

stoke/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4



class UserWallet(models.Model):
    COIN = [
        ('btc', 'btc'),
        ('ltc', 'ltc'),
        ('eth', 'eth'),
    ]

    id = models.UUIDField(default=uuid4, editable=False, primary_key=True, unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    balance = models.FloatField()
    address = models.CharField(max_length=50)
    currency = models.CharField(max_length=200, choices=COIN, default=COIN[0][0])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.user.username} | {self.currency.upper()} | {self.address}'

    def get_total_balance(self) -> int:
        total = 0
        user_transactions = self.objects.filter(user=self.user)
        for i in user_transactions:
            total + i.balance
        return total


class TransactionHistory(models.Model):
    COIN = [
        ('btc', 'btc'),
        ('ltc', 'ltc'),
        ('eth', 'eth'),
    ]

    TRANSACTION_TYPE = [
        ('out', 'out'),
        ('in', 'in'),
    ]
    id = models.UUIDField(default=uuid4, editable=False, primary_key=True, unique=True)
    transaction_ref = models.CharField(max_length=50, unique=True)
    # wallet = models.ForeignKey(to=UserWallet, on_delete=models.CASCADE)
    amount = models.IntegerField()
    transaction_type = models.CharField(max_length=3)
    currency = models.CharField(max_length=200, choices=COIN, default=COIN[0][0])
    from_address =  models.CharField(max_length=100)
    to_address =  models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'Currency: {self.currency} | Ref: {self.transaction_ref} | Sent From: {self.from_address} | Sent To: {self.to_address}'
    
    def get_total_received(self) -> int:
        total = 0
        user_transactions = self.objects.filter(transaction_type='in')
        for i in user_transactions:
            total + i.amount
        return total

    def get_total_sent(self):
        pass

core/forms.py
from django import forms
from .models import TransactionHistory



class SendCryptoModelForm(forms.ModelForm):
    class Meta:
        model = TransactionHistory
        exclude = ['transaction_ref', 'transaction_type', 'from_address', 'to_address']

core/views.py
from typing import Any
from uuid import uuid4
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.db.models.query import Q

from .models import TransactionHistory, UserWallet
from .forms import SendCryptoModelForm





def get_random_text(legnth: int) -> str:
    return uuid4().hex[:legnth]


class Dashboard(LoginRequiredMixin, ListView):
    template_name = 'core/dashboard.html'

    def get_queryset(self) -> QuerySet[Any]:
        return TransactionHistory.objects.filter(pk=self.request.user.pk)


class Wallet(LoginRequiredMixin, ListView):
    template_name = 'core/wallet.html'
    
    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)

        user_wallets = self.get_queryset()
        eth_wallet_address = user_wallets.get(currency='eth').address
        btc_wallet_address = user_wallets.get(currency='btc').address
        ltc_wallet_address = user_wallets.get(currency='ltc').address

        all_sent_transaction = TransactionHistory.objects.filter(
            Q(from_address=eth_wallet_address) | 
            Q(from_address=btc_wallet_address) | 
            Q(from_address=ltc_wallet_address) 
        ).order_by('-created_at')

        all_received_transaction = TransactionHistory.objects.filter(
            Q(to_address=eth_wallet_address) | 
            Q(to_address=btc_wallet_address) | 
            Q(to_address=ltc_wallet_address) 
        ).order_by('-created_at')

        # Get Total User Wallet Balance
        total_balance = 0.0
        for wallet in user_wallets: total_balance += wallet.balance

        total_sent_amount = 0.0
        for transaction in all_sent_transaction: total_sent_amount += transaction.amount

        total_received_amount = 0.0
        for transaction in all_received_transaction: total_received_amount += transaction.amount

        
        # Contexts]------------------------------------------
        # Sent Transactions
        context['all_sent_transactions'] = all_sent_transaction
        context['sent_eth_transactions'] = TransactionHistory.objects.filter(from_address=eth_wallet_address).order_by('-created_at')
        context['sent_btc_transactions'] = TransactionHistory.objects.filter(from_address=btc_wallet_address).order_by('-created_at')
        context['sent_ltc_transactions'] = TransactionHistory.objects.filter(from_address=ltc_wallet_address).order_by('-created_at')

        # Received Transactions
        context['all_received_transaction'] = all_received_transaction
        context['received_eth_transactions'] = TransactionHistory.objects.filter(to_address=eth_wallet_address).order_by('-created_at')
        context['received_btc_transactions'] = TransactionHistory.objects.filter(to_address=btc_wallet_address).order_by('-created_at')
        context['received_ltc_transactions'] = TransactionHistory.objects.filter(to_address=ltc_wallet_address).order_by('-created_at')
        
        # Totals
        context['total_balance'] = total_balance
        context['total_sent_amount'] = total_sent_amount
        context['total_received_amount'] = total_received_amount
        return context


class SendCrypto(LoginRequiredMixin, CreateView):
    template_name = 'core/crypto_send.html'
    form_class = SendCryptoModelForm

    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)

    def get_success_url(self) -> str:
        return resolve_url('core:wallet')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        try:
            send_amount = int(form.cleaned_data.get('amount'))
            currency = form.data.get('currency')
            address = form.data.get('address')
            wallet = UserWallet.objects.get(user=self.request.user.pk, currency=currency)
            recipient_wallet = UserWallet.objects.get(address=address)

            # check if send_amount is less than user wallet balance
            if send_amount > wallet.balance:
                return render(
                        self.request, 
                        'core/crypto_send.html', 
                        {
                            'form': form, 
                            'error': f'Insufficient {currency.upper()} balance', 
                            'wallets': UserWallet.objects.filter(user=self.request.user.pk)
                        }
                    )
        
            # deduct send_amount from user wallet balance
            wallet.balance -= send_amount
            wallet.save()

            # add send_amount from user to recipient's balance
            recipient_wallet.balance += send_amount
            recipient_wallet.save()

            form.instance.transaction_ref = get_random_text(20)
            form.instance.transaction_type = 'out'
            form.instance.from_address = wallet.address
            form.instance.to_address = address
            form.instance.currency = currency
            
            return super().form_valid(form)
        
        except UserWallet.DoesNotExist:
            return render(
                        self.request, 
                        'core/crypto_send.html', 
                        {
                            'form': form, 
                            'error': f'Invalid wallet address', 
                            'wallets': UserWallet.objects.filter(user=self.request.user.pk)
                        }
                    )

    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['wallets'] = UserWallet.objects.filter(user=self.request.user.pk)
        return context


class ReceiveCrypto(LoginRequiredMixin, ListView):
    template_name = 'core/crypto_receive.html'

    def get_queryset(self) -> QuerySet[Any]:
        return UserWallet.objects.filter(user=self.request.user.pk)


class CreateUser(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'core/register.html'
    success_url = '/login'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        # Create 3 User Wallets
        user = form.save()
        # ETH Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='eth',
        )
        # BTC Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='btc',
        )
        # LTH Wallet--------------------------------
        UserWallet.objects.create(
            user=user,
            balance=0.0,
            address=uuid4(),
            currency='ltc',
        )
        return super().form_valid(form)

def logout_user(request):
    logout(request)
    return redirect('core:login')

templates/core/auth_form_base_template.html
{% extends 'core/base_layout.html' %}
{% load static %}
{% block content %}
<div class="account-pages my-5 pt-sm-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-5">
                <div class="card overflow-hidden">
                    <div class="bg-primary bg-soft">
                        <div class="row">
                            <div class="col-7">
                                <div class="text-primary p-4">
                                    <h5 class="text-primary">Welcome Back !</h5>
                                    <p>Sign in to continue to Skote.</p>
                                </div>
                            </div>
                            <div class="col-5 align-self-end">
                                <img src="{% static 'images/profile-img.png' %}" alt="" class="img-fluid">
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-0">
                        <div class="auth-logo">
                            <a href="#" class="auth-logo-light">
                                <div class="avatar-md profile-user-wid mb-4">
                                    <span class="avatar-title rounded-circle bg-light">
                                        <img src="{% static 'images/logo-light.svg' %}" alt="" class="rounded-circle"
                                            height="34">
                                    </span>
                                </div>
                            </a>

                            <a href="#" class="auth-logo-dark">
                                <div class="avatar-md profile-user-wid mb-4">
                                    <span class="avatar-title rounded-circle bg-light">
                                        <img src="{% static 'images/logo.svg' %}" alt="" class="rounded-circle"
                                            height="34">
                                    </span>
                                </div>
                            </a>
                        </div>
                        <div class="p-2">
                            {% if form.errors %}
                            {% for error in form.errors.values %}
                            <div class="alert alert-success text-center mb-4" role="alert">
                                {{ error }}
                            </div>
                            {% endfor %}

                            <!-- Insert Form Here -->
                            {% block form %}{% endblock form %}
                        </div>
                        <div class="mt-5 text-center">

                            <div>
                                <p>Don't have an account ? <a href="{% url 'core:register' %}"
                                        class="fw-medium text-primary"> Signup now </a> </p>
                                <p>©
                                    <script>document.write(new Date().getFullYear())</script> Skote. Crafted with <i
                                        class="mdi mdi-heart text-danger"></i> by Thisrupt
                                </p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- end account-pages -->
    </div>
</div>
{% endblock content %}

templates/core/base.html
{% extends 'core/base_layout.html' %}
{% load static %}

{% block body %}

<body data-sidebar="dark" data-layout-mode="light">

    <!-- <body data-layout="horizontal" data-topbar="dark"> -->

    <!-- Begin page -->
    <div id="layout-wrapper">

        {% include 'core/inc/header.html' %}


        <!-- ========== Left Sidebar Start ========== -->
        {% include 'core/inc/sidebar.html' %}




        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">
                    {% block content %}{% endblock content %}
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

            <!-- Transaction Modal -->
            <div class="modal fade transaction-detailModal" tabindex="-1" role="dialog"
                aria-labelledby="transaction-detailModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="transaction-detailModalLabel">Order Details</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p class="mb-2">Product id: <span class="text-primary">#SK2540</span></p>
                            <p class="mb-4">Billing Name: <span class="text-primary">Neal Matthews</span></p>

                            <div class="table-responsive">
                                <table class="table align-middle table-nowrap">
                                    <thead>
                                        <tr>
                                            <th scope="col">Product</th>
                                            <th scope="col">Product Name</th>
                                            <th scope="col">Price</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row">
                                                <div>
                                                    <img src="assets/images/product/img-7.png" alt="" class="avatar-sm">
                                                </div>
                                            </th>
                                            <td>
                                                <div>
                                                    <h5 class="text-truncate font-size-14">Wireless Headphone (Black)
                                                    </h5>
                                                    <p class="text-muted mb-0">$ 225 x 1</p>
                                                </div>
                                            </td>
                                            <td>$ 255</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">
                                                <div>
                                                    <img src="assets/images/product/img-4.png" alt="" class="avatar-sm">
                                                </div>
                                            </th>
                                            <td>
                                                <div>
                                                    <h5 class="text-truncate font-size-14">Phone patterned cases</h5>
                                                    <p class="text-muted mb-0">$ 145 x 1</p>
                                                </div>
                                            </td>
                                            <td>$ 145</td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <h6 class="m-0 text-right">Sub Total:</h6>
                                            </td>
                                            <td>
                                                $ 400
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <h6 class="m-0 text-right">Shipping:</h6>
                                            </td>
                                            <td>
                                                Free
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <h6 class="m-0 text-right">Total:</h6>
                                            </td>
                                            <td>
                                                $ 400
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end modal -->

            <!-- subscribeModal -->
            <!-- <div class="modal fade" id="subscribeModal" tabindex="-1" aria-labelledby="subscribeModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header border-bottom-0">
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="text-center mb-4">
                                <div class="avatar-md mx-auto mb-4">
                                    <div class="avatar-title bg-light rounded-circle text-primary h1">
                                        <i class="mdi mdi-email-open"></i>
                                    </div>
                                </div>

                                <div class="row justify-content-center">
                                    <div class="col-xl-10">
                                        <h4 class="text-primary">Subscribe !</h4>
                                        <p class="text-muted font-size-14 mb-4">Subscribe our newletter and get
                                            notification to stay update.</p>

                                        <div class="input-group bg-light rounded">
                                            <input type="email" class="form-control bg-transparent border-0"
                                                placeholder="Enter Email address" aria-label="Recipient's username"
                                                aria-describedby="button-addon2">

                                            <button class="btn btn-primary" type="button" id="button-addon2">
                                                <i class="bx bxs-paper-plane"></i>
                                            </button>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->
            <!-- end modal -->

            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Skote.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Themesbrand
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <!-- end main content-->

    </div>
    <!-- END layout-wrapper -->

    <!-- Right Sidebar -->
    <div class="right-bar">
        <div data-simplebar class="h-100">
            <div class="rightbar-title d-flex align-items-center px-3 py-4">

                <h5 class="m-0 me-2">Settings</h5>

                <a href="javascript:void(0);" class="right-bar-toggle ms-auto">
                    <i class="mdi mdi-close noti-icon"></i>
                </a>
            </div>

            <!-- Settings -->
            <hr class="mt-0" />
            <h6 class="text-center mb-0">Choose Layouts</h6>

            <div class="p-4">
                <div class="mb-2">
                    <img src="assets/images/layouts/layout-1.jpg" class="img-thumbnail" alt="layout images">
                </div>

                <div class="form-check form-switch mb-3">
                    <input class="form-check-input theme-choice" type="checkbox" id="light-mode-switch" checked>
                    <label class="form-check-label" for="light-mode-switch">Light Mode</label>
                </div>

                <div class="mb-2">
                    <img src="assets/images/layouts/layout-2.jpg" class="img-thumbnail" alt="layout images">
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input theme-choice" type="checkbox" id="dark-mode-switch">
                    <label class="form-check-label" for="dark-mode-switch">Dark Mode</label>
                </div>

                <div class="mb-2">
                    <img src="assets/images/layouts/layout-3.jpg" class="img-thumbnail" alt="layout images">
                </div>
                <div class="form-check form-switch mb-3">
                    <input class="form-check-input theme-choice" type="checkbox" id="rtl-mode-switch">
                    <label class="form-check-label" for="rtl-mode-switch">RTL Mode</label>
                </div>

                <div class="mb-2">
                    <img src="assets/images/layouts/layout-4.jpg" class="img-thumbnail" alt="layout images">
                </div>
                <div class="form-check form-switch mb-5">
                    <input class="form-check-input theme-choice" type="checkbox" id="dark-rtl-mode-switch">
                    <label class="form-check-label" for="dark-rtl-mode-switch">Dark RTL Mode</label>
                </div>


            </div>

        </div> <!-- end slimscroll-menu-->
    </div>
    <!-- /Right-bar -->

    <!-- Right bar overlay-->
    <div class="rightbar-overlay"></div>

    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'libs/metismenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'libs/node-waves/waves.min.js' %}"></script>

    <!-- apexcharts -->
    <script src="{% static 'libs/apexcharts/apexcharts.min.js' %}"></script>

    <!-- dashboard init -->
    <script src="{% static 'js/pages/dashboard.init.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'js/app.js' %}"></script>
</body>
{% endblock body %}

templates/core/base_layout.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Dashboard | Skote</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />

    <!-- Font Face | ICONS -->
    <style>
        @charset "UTF-8";

        @font-face {
            font-family: "Material Design Icons";
            src: url("{% static 'fonts/materialdesignicons-webfont.eot?v=5.8.55' %}");
            src: url("{% static 'fonts/materialdesignicons-webfont.eot?#iefix&v=5.8.55' %}") format("embedded-opentype"),
            url("{% static 'fonts/materialdesignicons-webfont.woff2?v=5.8.55' %}") format("woff2"),
            url("{% static 'fonts/materialdesignicons-webfont.woff?v=5.8.55' %}") format("woff"),
            url("{% static 'fonts/materialdesignicons-webfont.ttf?v=5.8.55' %}") format("truetype");
            font-weight: 400;
            font-style: normal;
        }

        @font-face {
            font-family: boxicons;
            font-weight: 400;
            font-style: normal;
            src: url("{% static 'fonts/boxicons.eot' %}");
            src: url("{% static 'fonts/boxicons.eot' %}") format("embedded-opentype"),
            url("{% static 'fonts/boxicons.woff2' %}") format("woff2"),
            url("{% static 'fonts/boxicons.woff' %}") format("woff"),
            url("{% static 'fonts/boxicons.ttf' %}") format("truetype"),
            url("{% static 'fonts/boxicons.svg?#boxicons' %}") format("svg");
        }

        @font-face {
            font-family: "Font Awesome 5 Brands";
            font-style: normal;
            font-weight: 400;
            font-display: block;
            src: url('static "fonts/fa-brands-400.eot" %}');
            src: url('static "fonts/fa-brands-400.eot?#iefix" %}') format("embedded-opentype"),
                url('static "fonts/fa-brands-400.woff2" %}') format("woff2"),
                url('static "fonts/fa-brands-400.woff" %}') format("woff"),
                url('static "fonts/fa-brands-400.ttf" %}') format("truetype"),
                url('static "fonts/fa-brands-400.svg#fontawesome" %}') format("svg");
        }

        @font-face {
            font-family: "Font Awesome 5 Free";
            font-style: normal;
            font-weight: 400;
            font-display: block;
            src: url("{% static 'fonts/fa-regular-400.eot' %}");
            src: url("{% static 'fonts/fa-regular-400.eot?#iefix' %}") format("embedded-opentype"),
            url("{% static 'fonts/fa-regular-400.woff2' %}") format("woff2"),
            url("{% static 'fonts/fa-regular-400.woff' %}") format("woff"),
            url("{% static 'fonts/fa-regular-400.ttf' %}") format("truetype"),
            url("{% static 'fonts/fa-regular-400.svg#fontawesome' %}") format("svg");
        }

        @font-face {
            font-family: "Font Awesome 5 Free";
            font-style: normal;
            font-weight: 900;
            font-display: block;
            src: url("{% static 'fonts/fa-solid-900.eot' %}");
            src: url("{% static 'fonts/fa-solid-900.eot?#iefix' %}") format("embedded-opentype"),
            url("{% static 'fonts/fa-solid-900.woff2' %}") format("woff2"),
            url("{% static 'fonts/fa-solid-900.woff' %}") format("woff"),
            url("{% static 'fonts/fa-solid-900.ttf' %}") format("truetype"),
            url("{% static 'fonts/fa-solid-900.svg#fontawesome' %}") format("svg");
        }

        @font-face {
            font-family: dripicons-v2;
            src: url("{% static 'fonts/dripicons-v2.eot' %}");
            src: url("{% static 'fonts/dripicons-v2.eot?#iefix' %}") format("embedded-opentype"),
            url("{% static 'fonts/dripicons-v2.woff' %}") format("woff"),
            url("{% static 'fonts/dripicons-v2.ttf' %}") format("truetype"),
            url("{% static 'fonts/dripicons-v2.svg#dripicons-v2' %}") format("svg");
            font-weight: 400;
            font-style: normal;
        }
    </style>

</head>

{% block body %}
<body>
    {% block content %}{% endblock content %}
    
    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'libs/metismenu/metisMenu.min.js' %}"></script>
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
    <script src="{% static 'libs/node-waves/waves.min.js' %}"></script>

    <!-- apexcharts -->
    <script src="{% static 'libs/apexcharts/apexcharts.min.js' %}"></script>

    <!-- dashboard init -->
    <script src="{% static 'js/pages/dashboard.init.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'js/app.js' %}"></script>
</body>
{% endblock body %}

</html>